"""add docket number to invoices

Revision ID: 603f73264a5b
Revises: 
Create Date: 2026-01-21 11:11:58.229697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603f73264a5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('docket_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_docket_number'), 'invoices', ['docket_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_docket_number'), table_name='invoices')
    op.drop_column('invoices', 'docket_number')
    # ### end Alembic commands ###
