"""add invoice payments and remove is_paid

Revision ID: e358627a3290
Revises: 603f73264a5b
Create Date: 2026-01-21 11:26:23.139564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e358627a3290'
down_revision: Union[str, Sequence[str], None] = '603f73264a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payments', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('invoices', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_paid', sa.BOOLEAN(), nullable=True))
    op.drop_column('invoice_payments', 'note')
    # ### end Alembic commands ###
